// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnZ9L5pnXGr0aPjGT2kWxT2Uw8C3PcSZQ',
    appId: '1:162792758891:android:4fa82ffed1f02d5b351b2e',
    messagingSenderId: '162792758891',
    projectId: 'flutter-fcm-dbe9d',
    storageBucket: 'flutter-fcm-dbe9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbeOwb9osNaOX0wT9pEXnUP_ISeLF7Dco',
    appId: '1:162792758891:ios:e5486b6fc7ee360c351b2e',
    messagingSenderId: '162792758891',
    projectId: 'flutter-fcm-dbe9d',
    storageBucket: 'flutter-fcm-dbe9d.appspot.com',
    iosClientId: '162792758891-pegbo2oatljkjjk43c5jdrbq6ktsccim.apps.googleusercontent.com',
    iosBundleId: 'strokeRehabilitationApp',
  );
}
